[workspace]
members = [
  "crates/axonyx-core",
  "crates/axonyx-macros",
  "crates/axonyx-runtime",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/vladanPro/axonyx-runtime"
homepage = "https://github.com/vladanPro/axonyx-runtime"
documentation = "https://github.com/vladanPro/axonyx-runtime"
rust-version = "1.82"
version = "0.1.14"

[workspace.dependencies]
thiserror = "2.0.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
hmac = "0.12.1"
sha2 = "0.10.9"
axum = "0.8.9"
bytes = "1.11.1"
futures-util = "0.3.32"
tokio = "1.52.3"
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = { version = "2.0.117", features = ["full"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
