[package]
name = "axonyx-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true
description = "Core parser, lowering, query model, and SQL draft compiler for Axonyx"
readme = "../../README.md"
keywords = ["axonyx", "parser", "compiler", "ui", "rust"]
categories = ["compilers", "web-programming"]

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
axonyx-macros = { version = "0.1.0", path = "../axonyx-macros" }
