use thiserror::Error;

use crate::ax_backend_lowering::prelude::*;
use crate::ax_backend_parser::{parse_backend_ax, AxBackendParseError};

#[derive(Debug, Error, PartialEq, Eq)]
pub enum AxBackendCodegenError {
    #[error("route path is required to generate a route handler")]
    MissingRoutePath,
    #[error("domain helper `{function}` parameter `{field}` cannot be optional or defaulted yet")]
    UnsupportedFunctionDefaultInput { function: String, field: String },
    #[error("domain helper `{function}` cannot use query-backed data binding `{binding}` yet")]
    UnsupportedFunctionQueryBinding { function: String, binding: String },
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum AxBackendCompileError {
    #[error("backend parse failed: {0}")]
    Parse(#[from] AxBackendParseError),
    #[error("backend lowering failed: {0}")]
    Lower(#[from] AxBackendLowerError),
    #[error("backend code generation failed: {0}")]
    Codegen(#[from] AxBackendCodegenError),
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum AxBackendBundleError {
    #[error("backend source `{name}` failed to compile: {source}")]
    Source {
        name: String,
        #[source]
        source: AxBackendCompileError,
    },
}

pub fn generate_backend_module(plan: &AxBackendPlan) -> Result<String, AxBackendCodegenError> {
    let mut out = String::new();
    out.push_str("// @generated by Axonyx backend draft codegen\n");
    out.push_str("#![allow(dead_code, non_snake_case, unused_variables)]\n\n");
    out.push_str("use std::collections::BTreeMap;\n\n");
    out.push_str("use axonyx_runtime::backend_prelude::*;\n");
    out.push_str("use axonyx_runtime::server_prelude::*;\n");
    out.push_str("use serde_json::{json, Value};\n\n");
    out.push_str("fn __ax_finalize_response(mut response: AxHttpResponse, headers: BTreeMap<String, String>, cookies: Vec<AxCookie>) -> AxHttpResponse {\n");
    out.push_str("    for (name, value) in headers {\n");
    out.push_str("        response = response.with_header(name, value);\n");
    out.push_str("    }\n");
    out.push_str("    for cookie in cookies {\n");
    out.push_str("        response = response.with_cookie(cookie);\n");
    out.push_str("    }\n");
    out.push_str("    response\n");
    out.push_str("}\n\n");
    out.push_str("fn __ax_action_payload(payload: Value, patches: Vec<Value>, invalidations: Vec<Value>, redirect: Option<String>) -> Value {\n");
    out.push_str("    json!({ \"ok\": true, \"redirect\": redirect, \"value\": payload, \"patches\": patches, \"invalidations\": invalidations, \"refreshes\": [] })\n");
    out.push_str("}\n\n");
    out.push_str("fn __ax_action_error_payload(message: String, value: Value, status: u16, redirect: Option<String>) -> Value {\n");
    out.push_str("    json!({ \"ok\": false, \"redirect\": redirect, \"error\": { \"message\": message, \"status\": status, \"value\": value }, \"patches\": [], \"invalidations\": [], \"refreshes\": [] })\n");
    out.push_str("}\n\n");
    out.push_str("fn __ax_truthy(value: &Value) -> bool {\n");
    out.push_str("    match value { Value::Null => false, Value::Bool(value) => *value, Value::Number(_) => true, Value::String(value) => !value.is_empty(), Value::Array(items) => !items.is_empty(), Value::Object(fields) => !fields.is_empty() }\n");
    out.push_str("}\n\n");
    out.push_str("fn __ax_push_invalidation(invalidations: &mut Vec<Value>, target: String, explicit: bool) {\n");
    out.push_str("    let normalized = { let value = target.trim().trim_matches('\\\"').trim_matches('/'); if value.is_empty() { \"root\".to_string() } else { value.replace('/', \".\") } };\n");
    out.push_str("    let value = json!({ \"target\": target, \"queryKey\": [normalized] });\n");
    out.push_str("    let position = invalidations.iter().position(|item| item.get(\"queryKey\") == value.get(\"queryKey\"));\n");
    out.push_str("    match (position, explicit) { (Some(index), true) => invalidations[index] = value, (None, _) => invalidations.push(value), _ => {} }\n");
    out.push_str("}\n\n");
    out.push_str(
        "fn __ax_request_input_field(request: &AxHttpRequest, name: &str) -> Option<String> {\n",
    );
    out.push_str("    request.form_value(name).or_else(|| request.json_field_string(name))\n");
    out.push_str("}\n\n");
    out.push_str("fn __ax_loader_input_field(request: &AxHttpRequest, args: &[Value], index: usize, name: &str) -> Option<String> {\n");
    out.push_str("    args.get(index).and_then(|value| match value { Value::Null => None, Value::String(value) => Some(value.clone()), Value::Bool(value) => Some(value.to_string()), Value::Number(value) => Some(value.to_string()), Value::Array(_) | Value::Object(_) => Some(value.to_string()) }).or_else(|| __ax_request_input_field(request, name))\n");
    out.push_str("}\n\n");

    for function in &plan.functions {
        out.push_str(&render_function_fn(function)?);
        out.push('\n');
    }

    for handler in &plan.handlers {
        if let Some(input) = handler_input_fields(handler) {
            out.push_str(&render_input_struct(handler, input));
            out.push('\n');
        }

        out.push_str(&render_handler_fn(handler, &plan.globals)?);
        out.push('\n');
    }

    out.push_str(&render_compiled_dispatchers(&plan.handlers));

    Ok(out)
}

fn render_function_fn(function: &AxFunctionPlan) -> Result<String, AxBackendCodegenError> {
    for field in &function.input {
        if field.optional || field.default.is_some() {
            return Err(AxBackendCodegenError::UnsupportedFunctionDefaultInput {
                function: function.name.clone(),
                field: field.name.clone(),
            });
        }
    }

    let params = function
        .input
        .iter()
        .map(|field| format!("{}: {}", field.name, field.rust_ty))
        .collect::<Vec<_>>()
        .join(", ");
    let returns = function
        .returns
        .as_deref()
        .map(map_backend_return_type)
        .unwrap_or_else(|| "Value".to_string());

    let mut out = format!("pub fn {}({params}) -> {returns} {{\n", function.name);
    for step in &function.steps {
        out.push_str(&render_function_step(step, &returns, &function.name)?);
    }
    if !function
        .steps
        .iter()
        .any(|step| matches!(step, AxStepPlan::Return(_)))
    {
        out.push_str(&format!("    {}\n", default_function_return_expr(&returns)));
    }
    out.push_str("}\n");
    Ok(out)
}

fn render_function_step(
    step: &AxStepPlan,
    returns: &str,
    function: &str,
) -> Result<String, AxBackendCodegenError> {
    match step {
        AxStepPlan::Let { binding, value } => Ok(format!(
            "    let {binding} = {};\n",
            render_function_value_plan(value, function, binding)?
        )),
        AxStepPlan::Return(value) => Ok(render_function_return(value, returns)),
        other => Ok(format!("    // unsupported domain fn step: {other:?}\n")),
    }
}

fn render_function_value_plan(
    value: &AxValuePlan,
    function: &str,
    binding: &str,
) -> Result<String, AxBackendCodegenError> {
    match value {
        AxValuePlan::Expr(expr) => Ok(render_owned_expr(expr)),
        AxValuePlan::Query(_) => Err(AxBackendCodegenError::UnsupportedFunctionQueryBinding {
            function: function.to_string(),
            binding: binding.to_string(),
        }),
    }
}

fn render_function_return(value: &AxReturnPlan, returns: &str) -> String {
    match value {
        AxReturnPlan::Expr(expr) | AxReturnPlan::Json(expr) => {
            format!("    return {};\n", coerce_return_expr(expr, returns))
        }
        AxReturnPlan::Ok => format!("    return {};\n", default_function_return_expr(returns)),
        AxReturnPlan::NoContent => {
            format!("    return {};\n", default_function_return_expr(returns))
        }
        AxReturnPlan::NotFound => {
            format!("    return {};\n", default_function_return_expr(returns))
        }
        AxReturnPlan::Redirect { .. } => {
            format!("    return {};\n", default_function_return_expr(returns))
        }
    }
}

fn coerce_return_expr(expr: &AxRustExpr, returns: &str) -> String {
    match returns {
        "String" => render_string_expr(expr),
        "Value" => format!("json!({})", render_borrowed_expr(expr)),
        _ => render_owned_expr(expr),
    }
}

fn default_function_return_expr(returns: &str) -> String {
    match returns {
        "String" => "String::new()".to_string(),
        "bool" => "false".to_string(),
        "i64" | "u64" => "0".to_string(),
        "f64" => "0.0".to_string(),
        "Value" => "Value::Null".to_string(),
        _ => "Default::default()".to_string(),
    }
}

fn map_backend_return_type(ty: &str) -> String {
    match ty.trim() {
        "string" | "String" => "String".to_string(),
        "bool" | "boolean" | "Bool" | "Boolean" => "bool".to_string(),
        "i64" | "int" | "integer" | "Int" | "Integer" => "i64".to_string(),
        "u64" => "u64".to_string(),
        "f64" | "float" | "number" | "Float" | "Number" => "f64".to_string(),
        "Value" | "Json" | "JSON" => "Value".to_string(),
        other => other.to_string(),
    }
}

pub fn compile_backend_ax_to_module(input: &str) -> Result<String, AxBackendCompileError> {
    let document = parse_backend_ax(input)?;
    let plan = lower_backend_document(&document)?;
    Ok(generate_backend_module(&plan)?)
}

pub fn compile_backend_sources_to_module(
    sources: &[(&str, &str)],
) -> Result<String, AxBackendBundleError> {
    let mut globals = Vec::new();
    let mut envs = Vec::new();
    let mut functions = Vec::new();
    let mut handlers = Vec::new();

    for (name, input) in sources {
        let document = parse_backend_ax(input).map_err(|source| AxBackendBundleError::Source {
            name: (*name).to_string(),
            source: AxBackendCompileError::Parse(source),
        })?;
        let plan =
            lower_backend_document(&document).map_err(|source| AxBackendBundleError::Source {
                name: (*name).to_string(),
                source: AxBackendCompileError::Lower(source),
            })?;
        envs.extend(plan.envs);
        globals.extend(plan.globals);
        functions.extend(plan.functions);
        handlers.extend(plan.handlers);
    }

    generate_backend_module(&AxBackendPlan::with_globals(
        envs, globals, functions, handlers,
    ))
    .map_err(|source| AxBackendBundleError::Source {
        name: "bundle".to_string(),
        source: AxBackendCompileError::Codegen(source),
    })
}

fn render_input_struct(handler: &AxHandlerPlan, input: &[AxFieldPlan]) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!(
        "pub struct {} {{\n",
        input_struct_name(&handler.rust_fn)
    ));

    for field in input {
        out.push_str(&format!("    pub {}: {},\n", field.name, field.rust_ty));
    }

    out.push_str("}\n");
    out
}

fn render_handler_fn(
    handler: &AxHandlerPlan,
    globals: &[AxStepPlan],
) -> Result<String, AxBackendCodegenError> {
    let signature = match &handler.kind {
        AxHandlerKind::Action { input, .. } if input.is_empty() => format!(
            "pub fn {}(runtime: &impl AxBackendRuntime) -> AxRuntimeResult<Value>",
            handler.rust_fn
        ),
        AxHandlerKind::Action { .. } => format!(
            "pub fn {}(runtime: &impl AxBackendRuntime, input: &{}) -> AxRuntimeResult<Value>",
            handler.rust_fn,
            input_struct_name(&handler.rust_fn)
        ),
        AxHandlerKind::Loader { input, .. } if input.is_empty() => format!(
            "pub fn {}(runtime: &impl AxBackendRuntime, context: &AxLoaderContext) -> AxRuntimeResult<Value>",
            handler.rust_fn
        ),
        AxHandlerKind::Loader { .. } => format!(
            "pub fn {}(runtime: &impl AxBackendRuntime, context: &AxLoaderContext, input: &{}) -> AxRuntimeResult<Value>",
            handler.rust_fn,
            input_struct_name(&handler.rust_fn)
        ),
        AxHandlerKind::Route { .. } => format!(
            "pub fn {}(runtime: &impl AxBackendRuntime, request: &AxHttpRequest) -> AxRuntimeResult<AxHttpResponse>",
            handler.rust_fn
        ),
        AxHandlerKind::Job => format!(
            "pub fn {}(runtime: &impl AxBackendRuntime) -> AxRuntimeResult<Value>",
            handler.rust_fn
        ),
    };

    let mut out = String::new();
    out.push_str(&signature);
    out.push_str(" {\n");

    if let AxHandlerKind::Route {
        method,
        path,
        input,
        ..
    } = &handler.kind
    {
        if path.is_empty() {
            return Err(AxBackendCodegenError::MissingRoutePath);
        }
        out.push_str(&format!("    // route {method} {path}\n"));
        out.push_str(&format!(
            "    let context = __ax_loader_context({path:?}, request)?;\n"
        ));
        if !input.is_empty() {
            out.push_str(&render_route_input_binding(handler, input));
        }
    }

    let route_response = matches!(&handler.kind, AxHandlerKind::Route { .. });
    let action_response = matches!(&handler.kind, AxHandlerKind::Action { .. });
    if route_response {
        out.push_str("    let mut __ax_headers: BTreeMap<String, String> = BTreeMap::new();\n");
        out.push_str("    let mut __ax_cookies: Vec<AxCookie> = Vec::new();\n");
    }
    if action_response {
        out.push_str("    let mut __ax_patches: Vec<Value> = Vec::new();\n");
        out.push_str("    let mut __ax_invalidations: Vec<Value> = Vec::new();\n");
        out.push_str("    let mut __ax_redirect: Option<String> = None;\n");
    }
    for step in globals.iter().chain(handler.steps.iter()) {
        out.push_str(&render_step(step, route_response, action_response));
    }

    if !handler
        .steps
        .iter()
        .any(|step| matches!(step, AxStepPlan::Return(_)))
    {
        if route_response {
            out.push_str("    Ok(__ax_finalize_response(AxHttpResponse::json(200, &ok_payload()).map_err(|error| AxRuntimeError::message(error.to_string()))?, __ax_headers, __ax_cookies))\n");
        } else if action_response {
            out.push_str("    Ok(__ax_action_payload(ok_payload(), __ax_patches, __ax_invalidations, __ax_redirect))\n");
        } else {
            out.push_str("    Ok(ok_payload())\n");
        }
    }

    out.push_str("}\n");
    Ok(out)
}

fn render_compiled_dispatchers(handlers: &[AxHandlerPlan]) -> String {
    let mut out = String::from(
        r#"fn __ax_request_path(target: &str) -> &str {
    target.split_once('?').map_or(target, |(path, _)| path)
}

fn __ax_route_params(pattern: &str, target: &str) -> Option<BTreeMap<String, String>> {
    let pattern = pattern.trim_matches('/').split('/').filter(|part| !part.is_empty()).collect::<Vec<_>>();
    let target = __ax_request_path(target).trim_matches('/').split('/').filter(|part| !part.is_empty()).collect::<Vec<_>>();
    if pattern.len() != target.len() { return None; }
    let mut params = BTreeMap::new();
    for (expected, actual) in pattern.into_iter().zip(target) {
        if let Some(name) = expected.strip_prefix(':') {
            params.insert(name.to_string(), actual.to_string());
        } else if expected != actual {
            return None;
        }
    }
    Some(params)
}

fn __ax_loader_context(pattern: &str, request: &AxHttpRequest) -> AxRuntimeResult<AxLoaderContext> {
    let params = __ax_route_params(pattern, &request.target)
        .ok_or_else(|| AxRuntimeError::message("compiled route did not match request"))?;
    let mut context = AxLoaderContext::new();
    for (name, value) in params { context = context.with_param(name, value); }
    if let Some((_, query)) = request.target.split_once('?') {
        for pair in query.split('&').filter(|pair| !pair.is_empty()) {
            let (name, value) = pair.split_once('=').unwrap_or((pair, ""));
            context = context.with_query(name.to_string(), value.to_string());
        }
    }
    Ok(context)
}

"#,
    );

    out.push_str("pub fn dispatch_api_route(runtime: &impl AxBackendRuntime, request: &AxHttpRequest) -> AxRuntimeResult<Option<AxHttpResponse>> {\n");
    for handler in handlers {
        let AxHandlerKind::Route { method, path, .. } = &handler.kind else {
            continue;
        };
        out.push_str(&format!(
            "    if request.method.eq_ignore_ascii_case({method:?}) && __ax_route_params({path:?}, &request.target).is_some() {{ return {}(runtime, request).map(Some); }}\n",
            handler.rust_fn
        ));
    }
    out.push_str("    Ok(None)\n}\n\n");

    out.push_str("pub fn dispatch_action(runtime: &impl AxBackendRuntime, name: &str, request: &AxHttpRequest) -> AxRuntimeResult<Option<Value>> {\n    match name {\n");
    for handler in handlers {
        let AxHandlerKind::Action { input, .. } = &handler.kind else {
            continue;
        };
        out.push_str(&format!("        {:?} => {{\n", handler.name));
        if input.is_empty() {
            out.push_str(&format!(
                "            {}(runtime).map(Some)\n",
                handler.rust_fn
            ));
        } else {
            out.push_str(&format!(
                "            let input = {} {{\n",
                input_struct_name(&handler.rust_fn)
            ));
            for field in input {
                out.push_str(&format!(
                    "                {}: {},\n",
                    field.name,
                    render_route_input_field(field)
                ));
            }
            out.push_str("            };\n");
            out.push_str(&format!(
                "            {}(runtime, &input).map(Some)\n",
                handler.rust_fn
            ));
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => Ok(None),\n    }\n}\n");

    out.push_str("\npub fn dispatch_loader(runtime: &impl AxBackendRuntime, name: &str, pattern: &str, request: &AxHttpRequest, args: &[Value]) -> AxRuntimeResult<Option<Value>> {\n    match name {\n");
    for handler in handlers {
        let AxHandlerKind::Loader { input, .. } = &handler.kind else {
            continue;
        };
        out.push_str(&format!("        {:?} => {{\n", handler.name));
        out.push_str("            let context = __ax_loader_context(pattern, request)?;\n");
        if input.is_empty() {
            out.push_str("            if !args.is_empty() { return Err(AxRuntimeError::message(\"compiled loader expected 0 arguments\")); }\n");
            out.push_str(&format!(
                "            {}(runtime, &context).map(Some)\n",
                handler.rust_fn
            ));
        } else {
            out.push_str(&format!(
                "            if args.len() > {} {{ return Err(AxRuntimeError::message(\"compiled loader received too many arguments\")); }}\n",
                input.len()
            ));
            out.push_str(&format!(
                "            let input = {} {{\n",
                input_struct_name(&handler.rust_fn)
            ));
            for (index, field) in input.iter().enumerate() {
                out.push_str(&format!(
                    "                {}: {},\n",
                    field.name,
                    render_loader_input_field(field, index)
                ));
            }
            out.push_str("            };\n");
            out.push_str(&format!(
                "            {}(runtime, &context, &input).map(Some)\n",
                handler.rust_fn
            ));
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => Ok(None),\n    }\n}\n");
    out
}

fn handler_input_fields(handler: &AxHandlerPlan) -> Option<&[AxFieldPlan]> {
    match &handler.kind {
        AxHandlerKind::Action { input, .. }
        | AxHandlerKind::Route { input, .. }
        | AxHandlerKind::Loader { input, .. }
            if !input.is_empty() =>
        {
            Some(input)
        }
        _ => None,
    }
}

fn render_route_input_binding(handler: &AxHandlerPlan, input: &[AxFieldPlan]) -> String {
    let mut out = format!(
        "    let input = {} {{\n",
        input_struct_name(&handler.rust_fn)
    );

    for field in input {
        out.push_str(&format!(
            "        {}: {},\n",
            field.name,
            render_route_input_field(field)
        ));
    }

    out.push_str("    };\n");
    out
}

fn render_route_input_field(field: &AxFieldPlan) -> String {
    let raw = format!("__ax_request_input_field(request, {:?})", field.name);
    render_input_field(field, &raw)
}

fn render_loader_input_field(field: &AxFieldPlan, index: usize) -> String {
    let raw = format!(
        "__ax_loader_input_field(request, args, {index}, {:?})",
        field.name
    );
    render_input_field(field, &raw)
}

fn render_input_field(field: &AxFieldPlan, raw: &str) -> String {
    let missing_error = format!("missing required input `{}`", field.name);

    if !field.optional && field.default.is_none() && field.rust_ty != "bool" {
        return match field.rust_ty.as_str() {
            "String" => format!("{raw}.ok_or_else(|| AxRuntimeError::message({missing_error:?}))?"),
            "i64" | "u64" | "f64" => format!(
                "{raw}.ok_or_else(|| AxRuntimeError::message({missing_error:?}))?.trim().parse::<{}>().map_err(|_| AxRuntimeError::message({:?}))?",
                field.rust_ty,
                format!("input `{}` expected {}", field.name, field.rust_ty)
            ),
            _ => format!("{raw}.ok_or_else(|| AxRuntimeError::message({missing_error:?}))?"),
        };
    }

    let missing = if let Some(default) = &field.default {
        render_owned_expr(default)
    } else if field.optional {
        default_value_for_rust_type(&field.rust_ty)
    } else if field.rust_ty == "bool" {
        "false".to_string()
    } else {
        unreachable!("required non-bool fields return before fallback rendering");
    };

    match field.rust_ty.as_str() {
        "String" => format!("{raw}.unwrap_or_else(|| ({missing}).to_string())"),
        "bool" => format!(
            "{raw}.map(|value| matches!(value.trim().to_ascii_lowercase().as_str(), \"true\" | \"1\" | \"on\" | \"yes\")).unwrap_or({missing})"
        ),
        "i64" | "u64" | "f64" => format!(
            "{raw}.map(|value| value.trim().parse::<{}>().map_err(|_| AxRuntimeError::message(format!(\"input `{}` expected {} but received `{{}}`\", value)))).transpose()?.unwrap_or({missing})",
            field.rust_ty, field.name, field.rust_ty
        ),
        _ => format!("{raw}.unwrap_or_else(|| ({missing}).to_string())"),
    }
}

fn default_value_for_rust_type(rust_ty: &str) -> String {
    match rust_ty {
        "String" => "String::new()".to_string(),
        "bool" => "false".to_string(),
        "i64" | "u64" => "0".to_string(),
        "f64" => "0.0".to_string(),
        _ => "Default::default()".to_string(),
    }
}

fn render_step(step: &AxStepPlan, route_response: bool, action_response: bool) -> String {
    match step {
        AxStepPlan::Let { binding, value } => {
            format!("    let {binding} = {};\n", render_value_plan(value))
        }
        AxStepPlan::Insert { collection, fields } => {
            let invalidation = if action_response {
                format!(
                    "    __ax_push_invalidation(&mut __ax_invalidations, {:?}.to_string(), false);\n",
                    collection
                )
            } else {
                String::new()
            };
            format!(
                "    runtime.insert(&AxInsertRequest {{\n        collection: {:?}.to_string(),\n        fields: {},\n    }})?;\n{invalidation}",
                collection,
                render_fields_map(fields)
            )
        }
        AxStepPlan::Update {
            collection,
            fields,
            filters,
        } => {
            let invalidation = if action_response {
                format!(
                    "    __ax_push_invalidation(&mut __ax_invalidations, {:?}.to_string(), false);\n",
                    collection
                )
            } else {
                String::new()
            };
            format!(
                "    runtime.update(&AxUpdateRequest {{\n        collection: {:?}.to_string(),\n        fields: {},\n        filters: {},\n    }})?;\n{invalidation}",
                collection,
                render_fields_map(fields),
                render_query_filters(filters)
            )
        }
        AxStepPlan::Delete { collection, filters } => {
            let invalidation = if action_response {
                format!(
                    "    __ax_push_invalidation(&mut __ax_invalidations, {:?}.to_string(), false);\n",
                    collection
                )
            } else {
                String::new()
            };
            format!(
                "    runtime.delete(&AxDeleteRequest {{\n        collection: {:?}.to_string(),\n        filters: {},\n    }})?;\n{invalidation}",
                collection,
                render_query_filters(filters)
            )
        }
        AxStepPlan::Revalidate { target, literal } => {
            let target = if *literal {
                render_literal_revalidation_target(target)
            } else {
                render_borrowed_expr(target)
            };
            if action_response {
                format!(
                    "    let __ax_revalidate_target = ({target}).to_string();\n    runtime.revalidate(&__ax_revalidate_target)?;\n    if __ax_revalidate_target.starts_with('/') {{ __ax_redirect = Some(__ax_revalidate_target.clone()); }}\n    __ax_push_invalidation(&mut __ax_invalidations, __ax_revalidate_target, true);\n"
                )
            } else {
                format!("    runtime.revalidate({target})?;\n")
            }
        }
        AxStepPlan::Patch { signal, value } => {
            if action_response {
                format!(
                    "    __ax_patches.push(json!({{\"op\":\"set\",\"signal\":{},\"value\":{},\"source\":\"action\"}}));\n",
                    render_string_expr(signal),
                    render_borrowed_expr(value)
                )
            } else {
                format!("    // patch {} = {}\n", signal.code, value.code)
            }
        }
        AxStepPlan::Hook { phase, value } if route_response => {
            render_route_hook_step(*phase, value)
        }
        AxStepPlan::Hook { phase, value } => {
            let phase = match phase {
                AxHookPhasePlan::Before => "before",
                AxHookPhasePlan::After => "after",
            };
            format!("    // {phase} hook {}\n", value.code)
        }
        AxStepPlan::Header { name, value } if route_response => format!(
            "    __ax_headers.insert({}, {});\n",
            render_string_expr(name),
            render_string_expr(value)
        ),
        AxStepPlan::Header { name, value } => {
            format!("    // header {} = {}\n", name.code, value.code)
        }
        AxStepPlan::Cookie { name, value } if route_response => format!(
            "    __ax_cookies.push(AxCookie::new({}, {}).with_path(\"/\"));\n",
            render_string_expr(name),
            render_string_expr(value)
        ),
        AxStepPlan::Cookie { name, value } => {
            format!("    // cookie {} = {}\n", name.code, value.code)
        }
        AxStepPlan::ClearCookie { name } if route_response => format!(
            "    __ax_cookies.push(AxCookie::new({}, \"\").with_path(\"/\").with_max_age(0));\n",
            render_string_expr(name)
        ),
        AxStepPlan::ClearCookie { name } => format!("    // clearCookie {}\n", name.code),
        AxStepPlan::Require { value, fallback } if route_response => format!(
            "    if {}.is_empty() {{\n{}    }}\n",
            render_string_expr(value),
            render_require_fallback(fallback.as_ref())
        ),
        AxStepPlan::Require { value, fallback } if action_response => format!(
            "    if !__ax_truthy(&json!({})) {{\n{}    }}\n",
            render_borrowed_expr(value),
            render_action_require_fallback(fallback.as_ref())
        ),
        AxStepPlan::Require { value, .. } => format!("    // require {}\n", value.code),
        AxStepPlan::Return(value) => render_return_step(value, route_response, action_response),
        AxStepPlan::Send { target, payload } => format!(
            "    runtime.send(&AxSendRequest {{\n        target: {:?}.to_string(),\n        payload: json!({}),\n    }})?;\n",
            target,
            render_borrowed_expr(payload)
        ),
    }
}

fn render_route_hook_step(phase: AxHookPhasePlan, value: &AxRustExpr) -> String {
    match value.code.as_str() {
        "Security.headers" => {
            "    __ax_headers.insert(\"X-Content-Type-Options\".to_string(), \"nosniff\".to_string());\n    __ax_headers.insert(\"Referrer-Policy\".to_string(), \"strict-origin-when-cross-origin\".to_string());\n".to_string()
        }
        "Cache.noStore" => {
            "    __ax_headers.insert(\"Cache-Control\".to_string(), \"no-store\".to_string());\n"
                .to_string()
        }
        "Auth.session" | "Auth.bearer" | "Auth.signedSession" => format!(
            "    if {}.is_empty() {{\n{}    }}\n",
            render_string_expr(value),
            render_require_fallback(None)
        ),
        _ => {
            let phase = match phase {
                AxHookPhasePlan::Before => "before",
                AxHookPhasePlan::After => "after",
            };
            format!("    // {phase} hook {}\n", value.code)
        }
    }
}

fn render_value_plan(value: &AxValuePlan) -> String {
    match value {
        AxValuePlan::Expr(expr) => format!("json!({})", render_borrowed_expr(expr)),
        AxValuePlan::Query(query) => match &query.source {
            AxQuerySourcePlan::RawSql { .. } => {
                format!("runtime.query(&{})?", render_raw_sql_query_plan(query))
            }
            _ => format!("runtime.load(&{})?", render_query_plan(query)),
        },
    }
}

fn render_query_plan(query: &AxQueryPlan) -> String {
    let filters = if query.filters.is_empty() {
        "vec![]".to_string()
    } else {
        let entries = query
            .filters
            .iter()
            .map(|filter| {
                format!(
                    "AxQueryFilterRequest {{ field: {:?}.to_string(), op: {}, value: json!({}) }}",
                    filter.field,
                    render_filter_op(filter.op),
                    render_borrowed_expr(&filter.value)
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        format!("vec![{entries}]")
    };

    let orders = if query.orders.is_empty() {
        "vec![]".to_string()
    } else {
        let entries = query
            .orders
            .iter()
            .map(|order| {
                format!(
                    "AxQueryOrderRequest {{ field: {:?}.to_string(), direction: {} }}",
                    order.field,
                    render_order_direction(order.direction)
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        format!("vec![{entries}]")
    };

    let source = match &query.source {
        AxQuerySourcePlan::Stream { collection } => format!("{collection:?}.to_string()"),
        AxQuerySourcePlan::ContentCollection { collection } => {
            format!("{collection:?}.to_string()")
        }
        AxQuerySourcePlan::RawSql { .. } => {
            unreachable!("raw sql queries are rendered by render_raw_sql_query_plan")
        }
    };

    format!(
        "AxQueryRequest {{ collection: {source}, filters: {filters}, orders: {orders}, limit: {}, offset: {}, mode: {} }}",
        render_option_u32(query.limit),
        render_option_u32(query.offset),
        render_query_mode(query.mode)
    )
}

fn render_query_mode(mode: AxQueryModePlan) -> &'static str {
    match mode {
        AxQueryModePlan::Many => "AxQueryMode::Many",
        AxQueryModePlan::First => "AxQueryMode::First",
    }
}

fn render_raw_sql_query_plan(query: &AxQueryPlan) -> String {
    let AxQuerySourcePlan::RawSql { sql, params } = &query.source else {
        unreachable!("raw sql renderer requires raw sql source");
    };

    let params = if params.is_empty() {
        "vec![]".to_string()
    } else {
        let entries = params
            .iter()
            .map(|param| format!("json!({})", render_borrowed_expr(param)))
            .collect::<Vec<_>>()
            .join(", ");
        format!("vec![{entries}]")
    };

    format!(
        "AxRawSqlRequest {{ sql: {:?}.to_string(), params: {params} }}",
        sql
    )
}

fn render_fields_map(fields: &[AxAssignmentPlan]) -> String {
    if fields.is_empty() {
        return "BTreeMap::new()".to_string();
    }

    let entries = fields
        .iter()
        .map(|field| {
            format!(
                "({:?}.to_string(), json!({}))",
                field.name,
                render_borrowed_expr(&field.value)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    format!("BTreeMap::from([{entries}])")
}

fn render_query_filters(filters: &[AxQueryFilterPlan]) -> String {
    if filters.is_empty() {
        return "Vec::new()".to_string();
    }

    let entries = filters
        .iter()
        .map(|filter| {
            format!(
                "AxQueryFilterRequest {{ field: {:?}.to_string(), op: {}, value: json!({}) }}",
                filter.field,
                render_filter_op(filter.op),
                render_borrowed_expr(&filter.value)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    format!("vec![{entries}]")
}

fn render_borrowed_expr(expr: &AxRustExpr) -> String {
    if let Some(context_expr) = render_context_lookup(&expr.code) {
        context_expr
    } else {
        format!("&{}", render_codegen_expr(&expr.code))
    }
}

fn render_literal_revalidation_target(expr: &AxRustExpr) -> String {
    let target = expr
        .code
        .trim()
        .trim_end_matches(".to_string()")
        .trim()
        .trim_matches('"')
        .to_string();
    format!("{target:?}")
}

fn render_owned_expr(expr: &AxRustExpr) -> String {
    render_context_lookup(&expr.code)
        .map(|value| value.trim_start_matches('&').to_string())
        .unwrap_or_else(|| render_codegen_expr(&expr.code))
}

fn render_codegen_expr(code: &str) -> String {
    let code = code.trim();
    let Some(inner) = code
        .strip_prefix("contains(")
        .and_then(|value| value.strip_suffix(')'))
    else {
        return code.to_string();
    };
    let Some((items, value)) = split_codegen_binary_args(inner) else {
        return code.to_string();
    };
    format!(
        "({}).contains(&{})",
        render_codegen_expr(items),
        render_codegen_expr(value)
    )
}

fn split_codegen_binary_args(input: &str) -> Option<(&str, &str)> {
    let mut depth = 0usize;
    let mut quote = None;
    let mut escaped = false;
    for (index, ch) in input.char_indices() {
        if let Some(active) = quote {
            if escaped {
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == active {
                quote = None;
            }
            continue;
        }
        match ch {
            '\'' | '"' => quote = Some(ch),
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => {
                let left = input[..index].trim();
                let right = input[index + ch.len_utf8()..].trim();
                return (!left.is_empty() && !right.is_empty()).then_some((left, right));
            }
            _ => {}
        }
    }
    None
}

fn render_string_expr(expr: &AxRustExpr) -> String {
    format!("({}).to_string()", render_owned_expr(expr))
}

fn render_return_step(value: &AxReturnPlan, route_response: bool, action_response: bool) -> String {
    if route_response {
        return match value {
            AxReturnPlan::Expr(expr) | AxReturnPlan::Json(expr) => format!(
                "    Ok(__ax_finalize_response(AxHttpResponse::json(200, &json!({})).map_err(|error| AxRuntimeError::message(error.to_string()))?, __ax_headers, __ax_cookies))\n",
                render_borrowed_expr(expr)
            ),
            AxReturnPlan::Redirect { target, status } => match status {
                Some(status) => format!(
                    "    Ok(__ax_finalize_response(AxHttpResponse::redirect_with_status({status}, {}), __ax_headers, __ax_cookies))\n",
                    render_owned_expr(target)
                ),
                None => format!(
                    "    Ok(__ax_finalize_response(AxHttpResponse::redirect({}), __ax_headers, __ax_cookies))\n",
                    render_owned_expr(target)
                ),
            },
            AxReturnPlan::NoContent => {
                "    Ok(__ax_finalize_response(AxHttpResponse::no_content(), __ax_headers, __ax_cookies))\n".to_string()
            }
            AxReturnPlan::NotFound => {
                "    Ok(__ax_finalize_response(AxHttpResponse::text(404, \"not found\"), __ax_headers, __ax_cookies))\n".to_string()
            }
            AxReturnPlan::Ok => {
                "    Ok(__ax_finalize_response(AxHttpResponse::json(200, &ok_payload()).map_err(|error| AxRuntimeError::message(error.to_string()))?, __ax_headers, __ax_cookies))\n".to_string()
            }
        };
    }

    if action_response {
        return match value {
            AxReturnPlan::Expr(expr) | AxReturnPlan::Json(expr) => format!(
                "    Ok(__ax_action_payload(json!({}), __ax_patches, __ax_invalidations, __ax_redirect))\n",
                render_borrowed_expr(expr)
            ),
            AxReturnPlan::Ok
            | AxReturnPlan::NoContent
            | AxReturnPlan::NotFound
            | AxReturnPlan::Redirect { .. } => {
                "    Ok(__ax_action_payload(ok_payload(), __ax_patches, __ax_invalidations, __ax_redirect))\n".to_string()
            }
        };
    }

    match value {
        AxReturnPlan::Expr(expr) | AxReturnPlan::Json(expr) => {
            format!("    Ok(json!({}))\n", render_borrowed_expr(expr))
        }
        AxReturnPlan::Ok
        | AxReturnPlan::NoContent
        | AxReturnPlan::NotFound
        | AxReturnPlan::Redirect { .. } => "    Ok(ok_payload())\n".to_string(),
    }
}

fn render_action_require_fallback(fallback: Option<&AxReturnPlan>) -> String {
    match fallback {
        Some(AxReturnPlan::Expr(expr)) | Some(AxReturnPlan::Json(expr)) => {
            if let Some(message) = render_error_call_message(expr) {
                return format!(
                    "        let __ax_error_message = ({message}).to_string();\n        let __ax_error_value = json!(&__ax_error_message);\n        return Ok(__ax_action_error_payload(__ax_error_message, __ax_error_value, 422, __ax_redirect));\n"
                );
            } else {
                let value = format!("json!({})", render_borrowed_expr(expr));
                return format!(
                    "        let __ax_error_value = {value};\n        let __ax_error_message = __ax_error_value.get(\"message\").or_else(|| __ax_error_value.get(\"error\")).and_then(Value::as_str).unwrap_or(\"Action requirement failed.\").to_string();\n        return Ok(__ax_action_error_payload(__ax_error_message, __ax_error_value, 422, __ax_redirect));\n"
                );
            }
        }
        Some(AxReturnPlan::Redirect { target, .. }) => {
            let value = render_string_expr(target);
            format!(
                "        let __ax_error_message = {value};\n        let __ax_error_value = json!(&__ax_error_message);\n        return Ok(__ax_action_error_payload(__ax_error_message, __ax_error_value, 422, __ax_redirect));\n"
            )
        }
        Some(AxReturnPlan::NotFound) => "        return Ok(__ax_action_error_payload(\"not found\".to_string(), json!(\"not found\"), 422, __ax_redirect));\n".to_string(),
        Some(AxReturnPlan::Ok) | Some(AxReturnPlan::NoContent) | None => "        return Ok(__ax_action_error_payload(\"Action requirement failed.\".to_string(), json!(\"Action requirement failed.\"), 422, __ax_redirect));\n".to_string(),
    }
}

fn render_require_fallback(fallback: Option<&AxReturnPlan>) -> String {
    let response = match fallback {
        Some(AxReturnPlan::Expr(expr)) | Some(AxReturnPlan::Json(expr)) => {
            if let Some(message) = render_error_call_message(expr) {
                format!(
                    "AxHttpResponse::json(401, &json!({{\"error\": {message}}})).map_err(|error| AxRuntimeError::message(error.to_string()))?"
                )
            } else {
                format!(
                    "AxHttpResponse::json(401, &json!({})).map_err(|error| AxRuntimeError::message(error.to_string()))?",
                    render_borrowed_expr(expr)
                )
            }
        }
        Some(AxReturnPlan::Redirect { target, status }) => match status {
            Some(status) => format!(
                "AxHttpResponse::redirect_with_status({status}, {})",
                render_owned_expr(target)
            ),
            None => format!("AxHttpResponse::redirect({})", render_owned_expr(target)),
        },
        Some(AxReturnPlan::NoContent) => "AxHttpResponse::no_content()".to_string(),
        Some(AxReturnPlan::NotFound) => "AxHttpResponse::text(404, \"not found\")".to_string(),
        Some(AxReturnPlan::Ok) => "AxHttpResponse::json(200, &ok_payload()).map_err(|error| AxRuntimeError::message(error.to_string()))?".to_string(),
        None => "AxHttpResponse::json(401, &json!({\"error\":\"unauthorized\"})).map_err(|error| AxRuntimeError::message(error.to_string()))?".to_string(),
    };

    format!("        return Ok(__ax_finalize_response({response}, __ax_headers, __ax_cookies));\n")
}

fn render_error_call_message(expr: &AxRustExpr) -> Option<String> {
    let code = expr.code.trim();
    let inner = code.strip_prefix("error(")?.strip_suffix(')')?.trim();
    if inner.is_empty() || inner.contains(',') {
        return None;
    }
    Some(render_borrowed_expr(&AxRustExpr::new(inner)))
}

fn render_context_lookup(code: &str) -> Option<String> {
    let (source, field) = code.split_once('.')?;
    match source {
        "params" => Some(format!("&context.param({field:?})?")),
        "query" => Some(format!("&context.query({field:?})?")),
        "request" => render_request_lookup(field),
        "Auth" => render_auth_lookup(field),
        _ => None,
    }
}

fn render_auth_lookup(field: &str) -> Option<String> {
    match field {
        "bearer" => Some("&AxAuth::bearer(request).unwrap_or_default()".to_string()),
        "session" => Some("&AxAuth::session(request).unwrap_or_default()".to_string()),
        "signedSession" => Some(
            "&AxAuth::signed_session(request, &runtime.env().secret(\"session_key\")?).unwrap_or_default()"
                .to_string(),
        ),
        _ => None,
    }
}

fn render_request_lookup(field: &str) -> Option<String> {
    match field {
        "method" => Some("&request.method".to_string()),
        "target" => Some("&request.target".to_string()),
        "body" => Some("&request.body_text_lossy()".to_string()),
        _ => {
            let (group, key) = field.split_once('.')?;
            match group {
                "cookies" => Some(format!(
                    "&request.cookie_value({key:?}).unwrap_or_default()"
                )),
                "headers" => Some(format!(
                    "&request.header_value({:?}).unwrap_or_default()",
                    denormalize_header_key(key)
                )),
                "form" => Some(format!("&request.form_value({key:?}).unwrap_or_default()")),
                "json" => Some(format!(
                    "&request.json_field_string({key:?}).unwrap_or_default()"
                )),
                _ => None,
            }
        }
    }
}

fn denormalize_header_key(key: &str) -> String {
    key.replace('_', "-")
}

fn render_filter_op(op: AxQueryFilterOpPlan) -> &'static str {
    match op {
        AxQueryFilterOpPlan::Eq => "AxQueryFilterOp::Eq",
        AxQueryFilterOpPlan::Ne => "AxQueryFilterOp::Ne",
        AxQueryFilterOpPlan::In => "AxQueryFilterOp::In",
        AxQueryFilterOpPlan::NotIn => "AxQueryFilterOp::NotIn",
        AxQueryFilterOpPlan::IsNull => "AxQueryFilterOp::IsNull",
        AxQueryFilterOpPlan::IsNotNull => "AxQueryFilterOp::IsNotNull",
    }
}

fn render_order_direction(direction: AxQueryOrderDirectionPlan) -> &'static str {
    match direction {
        AxQueryOrderDirectionPlan::Asc => "AxQueryOrderDirection::Asc",
        AxQueryOrderDirectionPlan::Desc => "AxQueryOrderDirection::Desc",
    }
}

fn render_option_u32(value: Option<u32>) -> String {
    match value {
        Some(value) => format!("Some({value})"),
        None => "None".to_string(),
    }
}

fn input_struct_name(rust_fn: &str) -> String {
    let (prefix, suffix) = rust_fn
        .strip_prefix("action_")
        .map(|suffix| ("Action", suffix))
        .or_else(|| {
            rust_fn
                .strip_prefix("route_")
                .map(|suffix| ("Route", suffix))
        })
        .unwrap_or(("Handler", rust_fn));
    let mut out = String::from(prefix);

    for part in suffix.split('_').filter(|part| !part.is_empty()) {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.extend(chars.map(|ch| ch.to_ascii_lowercase()));
        }
    }

    out.push_str("Input");
    out
}

pub mod prelude {
    pub use super::compile_backend_ax_to_module;
    pub use super::compile_backend_sources_to_module;
    pub use super::generate_backend_module;
    pub use super::AxBackendBundleError;
    pub use super::AxBackendCodegenError;
    pub use super::AxBackendCompileError;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ax_ast::prelude::AxExpr;
    use crate::ax_backend_ast::prelude::*;
    use crate::ax_backend_lowering::lower_backend_document;

    #[test]
    fn generates_loader_and_action_module_against_runtime_traits() {
        let document = AxBackendDocument::new([
            AxBackendBlock::Loader(AxLoader::new(
                "PostsList",
                [
                    AxBackendStmt::data(
                        "posts",
                        crate::ax_query_ast::prelude::AxQuerySpec::new(
                            crate::ax_query_ast::prelude::AxQuerySource::Stream {
                                collection: "posts".to_string(),
                            },
                        )
                        .limit(20),
                    ),
                    AxBackendStmt::r#return(AxExpr::ident("posts")),
                ],
            )),
            AxBackendBlock::Action(
                AxAction::new("CreatePost")
                    .input([
                        AxField::new("title", "string"),
                        AxField::new("featured", "bool"),
                    ])
                    .body([
                        AxBackendStmt::insert(
                            "posts",
                            [
                                AxAssignment::new("title", AxExpr::ident("input").member("title")),
                                AxAssignment::new(
                                    "featured",
                                    AxExpr::ident("input").member("featured"),
                                ),
                            ],
                        ),
                        AxBackendStmt::r#return("ok"),
                    ]),
            ),
        ]);

        let plan = lower_backend_document(&document).expect("document should lower");
        let module = generate_backend_module(&plan).expect("module should generate");

        assert!(module.contains("use axonyx_runtime::backend_prelude::*;"));
        assert!(module.contains("use axonyx_runtime::server_prelude::*;"));
        assert!(module.contains("#![allow(dead_code, non_snake_case, unused_variables)]"));
        assert!(module.contains(
            "pub fn loader_posts_list(runtime: &impl AxBackendRuntime, context: &AxLoaderContext)"
        ));
        assert!(module.contains("pub fn dispatch_loader(runtime: &impl AxBackendRuntime, name: &str, pattern: &str, request: &AxHttpRequest, args: &[Value])"));
        assert!(module.contains("\"PostsList\" =>"));
        assert!(module.contains("loader_posts_list(runtime, &context).map(Some)"));
        assert!(module.contains("runtime.load(&AxQueryRequest"));
        assert!(module.contains("pub struct ActionCreatePostInput"));
        assert!(module.contains("pub fn action_create_post(runtime: &impl AxBackendRuntime, input: &ActionCreatePostInput)"));
        assert!(module.contains("runtime.insert(&AxInsertRequest"));
        assert!(module.contains(
            "__ax_push_invalidation(&mut __ax_invalidations, \"posts\".to_string(), false)"
        ));
        assert!(module.contains("Ok(__ax_action_payload(ok_payload(), __ax_patches, __ax_invalidations, __ax_redirect))"));
    }

    #[test]
    fn compiles_backend_ax_source_directly_into_module() {
        let module = compile_backend_ax_to_module(
            r#"
loader PostsList
  data posts = db.posts.all()
    where status = "published"
    limit 12
  return posts
"#,
        )
        .expect("source should compile");

        assert!(module.contains(
            "pub fn loader_posts_list(runtime: &impl AxBackendRuntime, context: &AxLoaderContext)"
        ));
        assert!(module.contains("field: \"status\".to_string()"));
        assert!(module.contains("limit: Some(12)"));
    }

    #[test]
    fn compiles_action_patch_steps_into_payload_patches() {
        let module = compile_backend_ax_to_module(
            r#"
action SetTheme(theme: string) {
  patch ThemeSwitch.theme = input.theme
  return ok()
}
"#,
        )
        .expect("source should compile");

        assert!(module.contains("let mut __ax_patches: Vec<Value> = Vec::new();"));
        assert!(module.contains("__ax_patches.push(json!({\"op\":\"set\""));
        assert!(module.contains("\"signal\":(\"ThemeSwitch.theme\".to_string()).to_string()"));
        assert!(module.contains("\"value\":&input.theme"));
        assert!(module.contains("Ok(__ax_action_payload(ok_payload(), __ax_patches, __ax_invalidations, __ax_redirect))"));
        assert!(!module.contains("// patch"));
    }

    #[test]
    fn compiles_action_invalidations_redirect_and_validation_envelope() {
        let module = compile_backend_ax_to_module(
            r#"
action SaveTheme(theme: string) {
  require input.theme in ["silver", "bronze", "gold"] else error("Theme is required.")
  update settings
    theme: input.theme
    where({ id: 1 })
  revalidate "/settings"
  return ok()
}
"#,
        )
        .expect("source should compile");

        assert!(module.contains("let mut __ax_invalidations: Vec<Value> = Vec::new();"));
        assert!(module.contains("let mut __ax_redirect: Option<String> = None;"));
        assert!(module.contains("__ax_truthy(&json!(&(vec![\"silver\".to_string(), \"bronze\".to_string(), \"gold\".to_string()]).contains(&input.theme)))"));
        assert!(module.contains("__ax_action_error_payload"));
        assert!(module.contains(
            "__ax_push_invalidation(&mut __ax_invalidations, \"settings\".to_string(), false)"
        ));
        assert!(module.contains("__ax_revalidate_target.starts_with('/')"));
        assert!(module.contains(
            "__ax_push_invalidation(&mut __ax_invalidations, __ax_revalidate_target, true)"
        ));
        assert!(module.contains("\"refreshes\": []"));
    }

    #[test]
    fn compiles_query_function_inputs_into_loader_input_struct() {
        let module = compile_backend_ax_to_module(
            r#"
query loadPosts(status: String) -> Post[]
  data posts = db.posts.all()
    where status = input.status
  return posts
"#,
        )
        .expect("source should compile");

        assert!(module.contains("pub struct HandlerLoaderLoadPostsInput"));
        assert!(module.contains("pub status: String"));
        assert!(module.contains("pub fn loader_load_posts(runtime: &impl AxBackendRuntime, context: &AxLoaderContext, input: &HandlerLoaderLoadPostsInput)"));
        assert!(module.contains("value: json!(&input.status)"));
        assert!(module.contains("__ax_loader_input_field(request, args, 0, \"status\")"));
        assert!(module.contains("if args.len() > 1"));
    }

    #[test]
    fn compiles_exported_domain_functions_into_backend_module() {
        let module = compile_backend_sources_to_module(&[
            (
                "domain.ax",
                r#"
export fn normalizeStatus(status: String) -> String {
  return status
}
"#,
            ),
            (
                "loader.ax",
                r#"
loader PostsList
  data status = normalizeStatus("published")
  return status
"#,
            ),
        ])
        .expect("backend bundle should compile");

        assert!(module.contains("pub fn normalizeStatus(status: String) -> String"));
        assert!(module.contains("return (status).to_string();"));
        assert!(
            module.contains(r#"let status = json!(&normalizeStatus("published".to_string()));"#)
        );
    }

    #[test]
    fn rejects_optional_domain_function_params_until_default_call_lowering_exists() {
        let error = compile_backend_ax_to_module(
            r#"
export fn normalizeStatus(status?: String) -> String {
  return status
}
"#,
        )
        .expect_err("optional helper params should be rejected for now");

        assert_eq!(
            error,
            AxBackendCompileError::Codegen(
                AxBackendCodegenError::UnsupportedFunctionDefaultInput {
                    function: "normalizeStatus".to_string(),
                    field: "status".to_string(),
                }
            )
        );
    }

    #[test]
    fn rejects_query_backed_data_inside_domain_functions() {
        let error = compile_backend_ax_to_module(
            r#"
export fn loadPublishedPosts() -> Value {
  data posts = db.posts.all()
  return posts
}
"#,
        )
        .expect_err("query-backed helper data should be rejected for now");

        assert_eq!(
            error,
            AxBackendCompileError::Codegen(
                AxBackendCodegenError::UnsupportedFunctionQueryBinding {
                    function: "loadPublishedPosts".to_string(),
                    binding: "posts".to_string(),
                }
            )
        );
    }

    #[test]
    fn compiles_db_all_query_source_into_runtime_load() {
        let module = compile_backend_ax_to_module(
            r#"
loader PostsList
  data posts = db.posts.all()
  return posts
"#,
        )
        .expect("source should compile");

        assert!(module.contains("runtime.load(&AxQueryRequest"));
        assert!(module.contains(r#"collection: "posts".to_string()"#));
    }

    #[test]
    fn compiles_raw_sql_query_source_into_runtime_query() {
        let module = compile_backend_ax_to_module(
            r#"
loader PostsList
  data posts = db.query("select * from posts where status = ?", "published")
  return posts
"#,
        )
        .expect("source should compile");

        assert!(module.contains("runtime.query(&AxRawSqlRequest"));
        assert!(module.contains(r#"sql: "select * from posts where status = ?".to_string()"#));
        assert!(module.contains("params: vec![json!("));
        assert!(module.contains("published"));
    }

    #[test]
    fn compiles_loader_params_and_query_into_context_lookups() {
        let module = compile_backend_ax_to_module(
            r#"
loader PostDetail
  data posts = db.posts.all()
    where slug = params.slug
    where status = query.status
    limit 1
  return posts
"#,
        )
        .expect("source should compile");

        assert!(module.contains(
            "pub fn loader_post_detail(runtime: &impl AxBackendRuntime, context: &AxLoaderContext)"
        ));
        assert!(module.contains(r#"value: json!(&context.param("slug")?)"#));
        assert!(module.contains(r#"value: json!(&context.query("status")?)"#));
    }

    #[test]
    fn compiles_runtime_env_access_into_runtime_env_calls() {
        let module = compile_backend_ax_to_module(
            r#"
backend
  env PUBLIC_SITE_URL: Public<String>

loader PostsList
  data db_url = Runtime.Env.secret.db_url
  data app_name = Runtime.Env.public.app_name
  data site_url = env.PUBLIC_SITE_URL
  return app_name
"#,
        )
        .expect("source should compile");

        assert!(module.contains(r#"let db_url = json!(&runtime.env().secret("db_url")?);"#));
        assert!(module.contains(r#"let app_name = json!(&runtime.env().public("app_name")?);"#));
        assert!(
            module.contains(r#"let site_url = json!(&runtime.env().value("PUBLIC_SITE_URL")?);"#)
        );
    }

    #[test]
    fn bundles_multiple_backend_sources_into_single_module() {
        let module = compile_backend_sources_to_module(&[
            (
                "app/backend.ax",
                r#"
backend
  data themes = ["silver", "bronze", "gold"]
"#,
            ),
            (
                "app/posts/loader.ax",
                r#"
loader PostsList
  data posts = db.posts.all()
  return posts
"#,
            ),
            (
                "routes/api/posts.ax",
                r#"
route GET "/api/posts"
  data posts = db.posts.all()
  return posts
"#,
            ),
        ])
        .expect("sources should compile");

        assert!(module.contains(
            "pub fn loader_posts_list(runtime: &impl AxBackendRuntime, context: &AxLoaderContext)"
        ));
        assert!(module.contains(
            r#"let themes = json!(&vec!["silver".to_string(), "bronze".to_string(), "gold".to_string()]);"#
        ));
        assert!(module
            .contains("pub fn route_get_api_posts(runtime: &impl AxBackendRuntime, request: &AxHttpRequest) -> AxRuntimeResult<AxHttpResponse>"));
    }

    #[test]
    fn compiles_route_http_return_helpers_into_responses() {
        let module = compile_backend_ax_to_module(
            r#"
route GET "/api/posts"
  data posts = db.posts.all()
  return json(posts)

route GET "/go"
  return redirect("/next")

route DELETE "/api/posts"
  return noContent()

route GET "/missing"
  return notFound()
"#,
        )
        .expect("source should compile");

        assert!(module.contains("AxRuntimeResult<AxHttpResponse>"));
        assert!(module.contains("AxHttpResponse::json(200, &json!(&posts))"));
        assert!(module.contains(r#"AxHttpResponse::redirect("/next".to_string())"#));
        assert!(module.contains("AxHttpResponse::no_content()"));
        assert!(module.contains("AxHttpResponse::text(404, \"not found\")"));
    }

    #[test]
    fn compiles_route_response_metadata_into_response_finalizer() {
        let module = compile_backend_ax_to_module(
            r#"
route GET "/api/session"
  require request.cookies.session
  header "Cache-Control" = "no-store"
  cookie "theme" = "gold"
  clearCookie "flash"
  return json("ok")
"#,
        )
        .expect("source should compile");

        assert!(module.contains("let mut __ax_headers: BTreeMap<String, String>"));
        assert!(module.contains(
            "if (request.cookie_value(\"session\").unwrap_or_default()).to_string().is_empty()"
        ));
        assert!(module.contains("__ax_headers.insert((\"Cache-Control\".to_string()).to_string(), (\"no-store\".to_string()).to_string());"));
        assert!(module.contains("__ax_cookies.push(AxCookie::new((\"theme\".to_string()).to_string(), (\"gold\".to_string()).to_string()).with_path(\"/\"));"));
        assert!(module.contains("__ax_cookies.push(AxCookie::new((\"flash\".to_string()).to_string(), \"\").with_path(\"/\").with_max_age(0));"));
        assert!(module.contains("__ax_finalize_response(AxHttpResponse::json"));
    }

    #[test]
    fn compiles_route_hooks_into_known_response_policies() {
        let module = compile_backend_ax_to_module(
            r#"
route GET "/api/admin"
  before Security.headers
  before Auth.session
  after Cache.noStore
  return json("ok")
"#,
        )
        .expect("source should compile");

        assert!(module.contains(
            "__ax_headers.insert(\"X-Content-Type-Options\".to_string(), \"nosniff\".to_string())"
        ));
        assert!(module.contains(
            "__ax_headers.insert(\"Referrer-Policy\".to_string(), \"strict-origin-when-cross-origin\".to_string())"
        ));
        assert!(module
            .contains("if (AxAuth::session(request).unwrap_or_default()).to_string().is_empty()"));
        assert!(module.contains(
            "__ax_headers.insert(\"Cache-Control\".to_string(), \"no-store\".to_string())"
        ));
    }

    #[test]
    fn compiles_require_fallback_into_route_response() {
        let module = compile_backend_ax_to_module(
            r#"
route GET "/api/admin"
  require request.cookies.session else redirect("/login")
  return json("ok")
"#,
        )
        .expect("source should compile");

        assert!(module.contains(
            "if (request.cookie_value(\"session\").unwrap_or_default()).to_string().is_empty()"
        ));
        assert!(module.contains(r#"AxHttpResponse::redirect("/login".to_string())"#));
    }

    #[test]
    fn compiles_require_not_found_fallback_into_route_response() {
        let module = compile_backend_ax_to_module(
            r#"
route GET "/api/posts/:slug"
  data post = db.posts.first()
    .where({ slug: params.slug })
  require post else notFound()
  return json(post)
"#,
        )
        .expect("source should compile");

        assert!(module.contains("AxHttpResponse::text(404, \"not found\")"));
    }

    #[test]
    fn compiles_guard_fallback_into_route_error_response() {
        let module = compile_backend_ax_to_module(
            r#"
route GET "/api/theme"
  guard(request.query.theme, "Theme is required.")
  return json("ok")
"#,
        )
        .expect("source should compile");

        assert!(module.contains(r#"AxHttpResponse::json(401, &json!({"error":"#));
        assert!(!module.contains("error("));
    }

    #[test]
    fn compiles_route_request_context_into_request_helpers() {
        let module = compile_backend_ax_to_module(
            r#"
route POST "/api/session"
  data theme = request.cookies.theme
  data agent = request.headers.user_agent
  data body = request.body
  data title = request.form.title
  data slug = request.json.slug
  data token = Auth.bearer
  data session = Auth.session
  data signed = Auth.signedSession
  return json(theme)
"#,
        )
        .expect("source should compile");

        assert!(module.contains("request.cookie_value(\"theme\").unwrap_or_default()"));
        assert!(module.contains("request.header_value(\"user-agent\").unwrap_or_default()"));
        assert!(module.contains("request.body_text_lossy()"));
        assert!(module.contains("request.form_value(\"title\").unwrap_or_default()"));
        assert!(module.contains("request.json_field_string(\"slug\").unwrap_or_default()"));
        assert!(module.contains("AxAuth::bearer(request).unwrap_or_default()"));
        assert!(module.contains("AxAuth::session(request).unwrap_or_default()"));
        assert!(module
            .contains("AxAuth::signed_session(request, &runtime.env().secret(\"session_key\")?)"));
    }

    #[test]
    fn compiles_route_typed_input_into_request_coercion() {
        let module = compile_backend_ax_to_module(
            r#"
route POST "/api/posts"
  input:
    title: string
    count: i64
    featured?: bool = false

  return json(input.title)
"#,
        )
        .expect("source should compile");

        assert!(module.contains("pub struct RoutePostApiPostsInput"));
        assert!(module.contains("__ax_request_input_field(request, \"title\")"));
        assert!(module.contains("missing required input `title`"));
        assert!(module.contains("parse::<i64>()"));
        assert!(module.contains("let input = RoutePostApiPostsInput"));
        assert!(module.contains("AxHttpResponse::json(200, &json!(&input.title))"));
    }

    #[test]
    fn compiles_delete_where_into_runtime_delete_request() {
        let module = compile_backend_ax_to_module(
            r#"
action RemovePost
  input:
    id: i64

  delete "posts"
    where id = input.id

  return ok
"#,
        )
        .expect("source should compile");

        assert!(module.contains("runtime.delete(&AxDeleteRequest"));
        assert!(module.contains("filters: vec![AxQueryFilterRequest"));
        assert!(module.contains("field: \"id\".to_string()"));
    }

    #[test]
    fn generates_compiled_api_and_action_dispatchers() {
        let module = compile_backend_ax_to_module(
            r#"
route GET "/api/posts/:slug"
  data slug = params.slug
  return json(slug)

action PublishPost(id: i64) {
  update posts
    status: "published"
    where id = input.id
  return ok
}

action Refresh {
  return ok
}
"#,
        )
        .expect("source should compile");

        assert!(module.contains("pub fn dispatch_api_route"));
        assert!(module.contains("__ax_route_params(\"/api/posts/:slug\""));
        assert!(
            module.contains("let context = __ax_loader_context(\"/api/posts/:slug\", request)?")
        );
        assert!(module.contains("pub fn dispatch_action"));
        assert!(module.contains("\"PublishPost\" =>"));
        assert!(module.contains("let input = ActionPublishPostInput"));
        assert!(module.contains("\"Refresh\" =>"));
        assert!(module.contains("action_refresh(runtime).map(Some)"));
    }
}
