[package]
name = "axonyx-macros"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true
description = "Procedural macros for ergonomic Axonyx component authoring"
readme = "../../README.md"
keywords = ["axonyx", "macros", "proc-macro", "ui", "rust"]
categories = ["development-tools", "gui"]

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
